# Generated by Django 5.0.6 on 2024-08-02 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_user_reputation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cookie',
        ),
    ]
