# Generated by Django 5.0.8 on 2024-08-07 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=255)),
                ('course_type', models.CharField(choices=[('compulsory', 'Compulsory'), ('elective', 'Elective'), ('restricted_elective', 'Restricted Elective')], max_length=50)),
                ('college', models.CharField(max_length=255)),
                ('credits', models.DecimalField(decimal_places=2, max_digits=4)),
                ('course_teacher', models.CharField(max_length=255)),
                ('course_method', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('hybrid', 'Hybrid')], max_length=50)),
                ('assessment_method', models.CharField(max_length=255)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('publish_time', models.DateTimeField(auto_now_add=True)),
                ('relative_articles', models.ManyToManyField(related_name='courses', to='myapp.article')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('post_title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('tags', models.CharField(max_length=255)),
                ('views', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('block', models.BooleanField(default=False)),
                ('top', models.BooleanField(default=False)),
                ('publish_time', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='myapp.article')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='myapp.course')),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reply_content', models.TextField()),
                ('reply_time', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='myapp.post')),
                ('replier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
